# Generated by Django 4.1.5 on 2023-03-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
