# Generated by Django 4.1.5 on 2023-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_section_filter_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
