# Generated by Django 4.1.5 on 2023-03-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_request_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='busnesLogo',
            field=models.ImageField(blank=True, null=True, upload_to='MainPage/static/images/sell/'),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=3000, null=True),
        ),
    ]
