# Generated by Django 4.1.5 on 2023-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_alter_filter_filter_alter_section_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='link',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
