# Generated by Django 4.1.5 on 2023-03-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_section_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='link',
        ),
    ]
