# Generated by Django 4.1.5 on 2023-03-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_remove_business_busneslogo_business_bussineslogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='visible',
            new_name='public',
        ),
    ]
