# Generated by Django 4.1.5 on 2023-03-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_remove_section_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='link',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
