# Generated by Django 4.1.5 on 2023-03-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_remove_section_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('login', models.DateTimeField(default=None)),
                ('address', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=100)),
                ('product', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=None, max_length=50)),
                ('business', models.BooleanField(default=False)),
                ('sell', models.BooleanField(default=False)),
                ('buy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default=None, max_length=100)),
                ('eMaile', models.EmailField(default=None, max_length=254)),
                ('busines', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainPage.business')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainPage.request')),
            ],
            bases=('MainPage.request',),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainPage.request')),
                ('price', models.FloatField(default=None)),
            ],
            bases=('MainPage.request',),
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AddField(
            model_name='request',
            name='tags',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainPage.tag'),
        ),
        migrations.AddField(
            model_name='business',
            name='buy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainPage.buy'),
        ),
        migrations.AddField(
            model_name='business',
            name='sell',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainPage.sell'),
        ),
    ]
