# Generated by Django 4.1.5 on 2023-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_rename_number_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
