# Generated by Django 4.1.5 on 2023-03-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0008_request_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, default=True, null=True),
        ),
    ]
