# Generated by Django 4.1.5 on 2023-03-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_rename_emaile_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='busines',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='business_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainPage.business'),
            preserve_default=False,
        ),
    ]
