# Generated by Django 4.1.5 on 2023-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='MainPage/static/images/businesses/'),
        ),
    ]
