# Generated by Django 4.1.5 on 2023-03-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_alter_business_address_alter_business_buy_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
