# Generated by Django 4.1.5 on 2023-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0013_alter_business_address_alter_business_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
